package currency

/*-------------------------------+
| Code generated by std_currency |
|          DO NOT EDIT           |
+-------------------------------*/

import "fmt"

// Currency defines a currency containing
// It's code, taken from the constants above
// as well as it's minor units, as an integer.
type Currency struct {
	code       string
	minorUnits int
}

// Code returns the currency code to the user
func (c *Currency) Code() string { return c.code }

// MinorUnits returns the minor unit to the user
func (c *Currency) MinorUnits() int { return c.minorUnits }

// GetCurrency returns a currency struct if the provided
// code is contained within the valid codes. Otherwise
// an error will be returned
func GetCurrency(code string) (*Currency, error) {
	if Valid(code) {
		val, ok := currencies[code]
		if ok {
			return &val, nil
		}
	}
	return nil, fmt.Errorf("currency: could not find currency with code: %q", code)
}

// Valid checks if a provided code is contained
// inside the provided ValidCodes slice
func Valid(code string) bool {
	for _, c := range ValidCodes {
		if c == code {
			return true
		}
	}
	return false
}

var (
	// AFN currency struct
	AFN = Currency{code: "AFN", minorUnits: 2}
	// EUR currency struct
	EUR = Currency{code: "EUR", minorUnits: 2}
	// ALL currency struct
	ALL = Currency{code: "ALL", minorUnits: 2}
	// DZD currency struct
	DZD = Currency{code: "DZD", minorUnits: 2}
	// USD currency struct
	USD = Currency{code: "USD", minorUnits: 2}
	// AOA currency struct
	AOA = Currency{code: "AOA", minorUnits: 2}
	// XCD currency struct
	XCD = Currency{code: "XCD", minorUnits: 2}
	// ARS currency struct
	ARS = Currency{code: "ARS", minorUnits: 2}
	// AMD currency struct
	AMD = Currency{code: "AMD", minorUnits: 2}
	// AWG currency struct
	AWG = Currency{code: "AWG", minorUnits: 2}
	// AUD currency struct
	AUD = Currency{code: "AUD", minorUnits: 2}
	// AZN currency struct
	AZN = Currency{code: "AZN", minorUnits: 2}
	// BSD currency struct
	BSD = Currency{code: "BSD", minorUnits: 2}
	// BHD currency struct
	BHD = Currency{code: "BHD", minorUnits: 3}
	// BDT currency struct
	BDT = Currency{code: "BDT", minorUnits: 2}
	// BBD currency struct
	BBD = Currency{code: "BBD", minorUnits: 2}
	// BYN currency struct
	BYN = Currency{code: "BYN", minorUnits: 2}
	// BZD currency struct
	BZD = Currency{code: "BZD", minorUnits: 2}
	// XOF currency struct
	XOF = Currency{code: "XOF", minorUnits: 0}
	// BMD currency struct
	BMD = Currency{code: "BMD", minorUnits: 2}
	// INR currency struct
	INR = Currency{code: "INR", minorUnits: 2}
	// BTN currency struct
	BTN = Currency{code: "BTN", minorUnits: 2}
	// BOB currency struct
	BOB = Currency{code: "BOB", minorUnits: 2}
	// BOV currency struct
	BOV = Currency{code: "BOV", minorUnits: 2}
	// BAM currency struct
	BAM = Currency{code: "BAM", minorUnits: 2}
	// BWP currency struct
	BWP = Currency{code: "BWP", minorUnits: 2}
	// NOK currency struct
	NOK = Currency{code: "NOK", minorUnits: 2}
	// BRL currency struct
	BRL = Currency{code: "BRL", minorUnits: 2}
	// BND currency struct
	BND = Currency{code: "BND", minorUnits: 2}
	// BGN currency struct
	BGN = Currency{code: "BGN", minorUnits: 2}
	// BIF currency struct
	BIF = Currency{code: "BIF", minorUnits: 0}
	// CVE currency struct
	CVE = Currency{code: "CVE", minorUnits: 2}
	// KHR currency struct
	KHR = Currency{code: "KHR", minorUnits: 2}
	// XAF currency struct
	XAF = Currency{code: "XAF", minorUnits: 0}
	// CAD currency struct
	CAD = Currency{code: "CAD", minorUnits: 2}
	// KYD currency struct
	KYD = Currency{code: "KYD", minorUnits: 2}
	// CLP currency struct
	CLP = Currency{code: "CLP", minorUnits: 0}
	// CLF currency struct
	CLF = Currency{code: "CLF", minorUnits: 4}
	// CNY currency struct
	CNY = Currency{code: "CNY", minorUnits: 2}
	// COP currency struct
	COP = Currency{code: "COP", minorUnits: 2}
	// COU currency struct
	COU = Currency{code: "COU", minorUnits: 2}
	// KMF currency struct
	KMF = Currency{code: "KMF", minorUnits: 0}
	// CDF currency struct
	CDF = Currency{code: "CDF", minorUnits: 2}
	// NZD currency struct
	NZD = Currency{code: "NZD", minorUnits: 2}
	// CRC currency struct
	CRC = Currency{code: "CRC", minorUnits: 2}
	// HRK currency struct
	HRK = Currency{code: "HRK", minorUnits: 2}
	// CUP currency struct
	CUP = Currency{code: "CUP", minorUnits: 2}
	// CUC currency struct
	CUC = Currency{code: "CUC", minorUnits: 2}
	// ANG currency struct
	ANG = Currency{code: "ANG", minorUnits: 2}
	// CZK currency struct
	CZK = Currency{code: "CZK", minorUnits: 2}
	// DKK currency struct
	DKK = Currency{code: "DKK", minorUnits: 2}
	// DJF currency struct
	DJF = Currency{code: "DJF", minorUnits: 0}
	// DOP currency struct
	DOP = Currency{code: "DOP", minorUnits: 2}
	// EGP currency struct
	EGP = Currency{code: "EGP", minorUnits: 2}
	// SVC currency struct
	SVC = Currency{code: "SVC", minorUnits: 2}
	// ERN currency struct
	ERN = Currency{code: "ERN", minorUnits: 2}
	// ETB currency struct
	ETB = Currency{code: "ETB", minorUnits: 2}
	// FKP currency struct
	FKP = Currency{code: "FKP", minorUnits: 2}
	// FJD currency struct
	FJD = Currency{code: "FJD", minorUnits: 2}
	// XPF currency struct
	XPF = Currency{code: "XPF", minorUnits: 0}
	// GMD currency struct
	GMD = Currency{code: "GMD", minorUnits: 2}
	// GEL currency struct
	GEL = Currency{code: "GEL", minorUnits: 2}
	// GHS currency struct
	GHS = Currency{code: "GHS", minorUnits: 2}
	// GIP currency struct
	GIP = Currency{code: "GIP", minorUnits: 2}
	// GTQ currency struct
	GTQ = Currency{code: "GTQ", minorUnits: 2}
	// GBP currency struct
	GBP = Currency{code: "GBP", minorUnits: 2}
	// GNF currency struct
	GNF = Currency{code: "GNF", minorUnits: 0}
	// GYD currency struct
	GYD = Currency{code: "GYD", minorUnits: 2}
	// HTG currency struct
	HTG = Currency{code: "HTG", minorUnits: 2}
	// HNL currency struct
	HNL = Currency{code: "HNL", minorUnits: 2}
	// HKD currency struct
	HKD = Currency{code: "HKD", minorUnits: 2}
	// HUF currency struct
	HUF = Currency{code: "HUF", minorUnits: 2}
	// ISK currency struct
	ISK = Currency{code: "ISK", minorUnits: 0}
	// IDR currency struct
	IDR = Currency{code: "IDR", minorUnits: 2}
	// XDR currency struct
	XDR = Currency{code: "XDR", minorUnits: 0}
	// IRR currency struct
	IRR = Currency{code: "IRR", minorUnits: 2}
	// IQD currency struct
	IQD = Currency{code: "IQD", minorUnits: 3}
	// ILS currency struct
	ILS = Currency{code: "ILS", minorUnits: 2}
	// JMD currency struct
	JMD = Currency{code: "JMD", minorUnits: 2}
	// JPY currency struct
	JPY = Currency{code: "JPY", minorUnits: 0}
	// JOD currency struct
	JOD = Currency{code: "JOD", minorUnits: 3}
	// KZT currency struct
	KZT = Currency{code: "KZT", minorUnits: 2}
	// KES currency struct
	KES = Currency{code: "KES", minorUnits: 2}
	// KPW currency struct
	KPW = Currency{code: "KPW", minorUnits: 2}
	// KRW currency struct
	KRW = Currency{code: "KRW", minorUnits: 0}
	// KWD currency struct
	KWD = Currency{code: "KWD", minorUnits: 3}
	// KGS currency struct
	KGS = Currency{code: "KGS", minorUnits: 2}
	// LAK currency struct
	LAK = Currency{code: "LAK", minorUnits: 2}
	// LBP currency struct
	LBP = Currency{code: "LBP", minorUnits: 2}
	// LSL currency struct
	LSL = Currency{code: "LSL", minorUnits: 2}
	// ZAR currency struct
	ZAR = Currency{code: "ZAR", minorUnits: 2}
	// LRD currency struct
	LRD = Currency{code: "LRD", minorUnits: 2}
	// LYD currency struct
	LYD = Currency{code: "LYD", minorUnits: 3}
	// CHF currency struct
	CHF = Currency{code: "CHF", minorUnits: 2}
	// MOP currency struct
	MOP = Currency{code: "MOP", minorUnits: 2}
	// MKD currency struct
	MKD = Currency{code: "MKD", minorUnits: 2}
	// MGA currency struct
	MGA = Currency{code: "MGA", minorUnits: 2}
	// MWK currency struct
	MWK = Currency{code: "MWK", minorUnits: 2}
	// MYR currency struct
	MYR = Currency{code: "MYR", minorUnits: 2}
	// MVR currency struct
	MVR = Currency{code: "MVR", minorUnits: 2}
	// MRU currency struct
	MRU = Currency{code: "MRU", minorUnits: 2}
	// MUR currency struct
	MUR = Currency{code: "MUR", minorUnits: 2}
	// XUA currency struct
	XUA = Currency{code: "XUA", minorUnits: 0}
	// MXN currency struct
	MXN = Currency{code: "MXN", minorUnits: 2}
	// MXV currency struct
	MXV = Currency{code: "MXV", minorUnits: 2}
	// MDL currency struct
	MDL = Currency{code: "MDL", minorUnits: 2}
	// MNT currency struct
	MNT = Currency{code: "MNT", minorUnits: 2}
	// MAD currency struct
	MAD = Currency{code: "MAD", minorUnits: 2}
	// MZN currency struct
	MZN = Currency{code: "MZN", minorUnits: 2}
	// MMK currency struct
	MMK = Currency{code: "MMK", minorUnits: 2}
	// NAD currency struct
	NAD = Currency{code: "NAD", minorUnits: 2}
	// NPR currency struct
	NPR = Currency{code: "NPR", minorUnits: 2}
	// NIO currency struct
	NIO = Currency{code: "NIO", minorUnits: 2}
	// NGN currency struct
	NGN = Currency{code: "NGN", minorUnits: 2}
	// OMR currency struct
	OMR = Currency{code: "OMR", minorUnits: 3}
	// PKR currency struct
	PKR = Currency{code: "PKR", minorUnits: 2}
	// PAB currency struct
	PAB = Currency{code: "PAB", minorUnits: 2}
	// PGK currency struct
	PGK = Currency{code: "PGK", minorUnits: 2}
	// PYG currency struct
	PYG = Currency{code: "PYG", minorUnits: 0}
	// PEN currency struct
	PEN = Currency{code: "PEN", minorUnits: 2}
	// PHP currency struct
	PHP = Currency{code: "PHP", minorUnits: 2}
	// PLN currency struct
	PLN = Currency{code: "PLN", minorUnits: 2}
	// QAR currency struct
	QAR = Currency{code: "QAR", minorUnits: 2}
	// RON currency struct
	RON = Currency{code: "RON", minorUnits: 2}
	// RUB currency struct
	RUB = Currency{code: "RUB", minorUnits: 2}
	// RWF currency struct
	RWF = Currency{code: "RWF", minorUnits: 0}
	// SHP currency struct
	SHP = Currency{code: "SHP", minorUnits: 2}
	// WST currency struct
	WST = Currency{code: "WST", minorUnits: 2}
	// STN currency struct
	STN = Currency{code: "STN", minorUnits: 2}
	// SAR currency struct
	SAR = Currency{code: "SAR", minorUnits: 2}
	// RSD currency struct
	RSD = Currency{code: "RSD", minorUnits: 2}
	// SCR currency struct
	SCR = Currency{code: "SCR", minorUnits: 2}
	// SLL currency struct
	SLL = Currency{code: "SLL", minorUnits: 2}
	// SGD currency struct
	SGD = Currency{code: "SGD", minorUnits: 2}
	// XSU currency struct
	XSU = Currency{code: "XSU", minorUnits: 0}
	// SBD currency struct
	SBD = Currency{code: "SBD", minorUnits: 2}
	// SOS currency struct
	SOS = Currency{code: "SOS", minorUnits: 2}
	// SSP currency struct
	SSP = Currency{code: "SSP", minorUnits: 2}
	// LKR currency struct
	LKR = Currency{code: "LKR", minorUnits: 2}
	// SDG currency struct
	SDG = Currency{code: "SDG", minorUnits: 2}
	// SRD currency struct
	SRD = Currency{code: "SRD", minorUnits: 2}
	// SZL currency struct
	SZL = Currency{code: "SZL", minorUnits: 2}
	// SEK currency struct
	SEK = Currency{code: "SEK", minorUnits: 2}
	// CHE currency struct
	CHE = Currency{code: "CHE", minorUnits: 2}
	// CHW currency struct
	CHW = Currency{code: "CHW", minorUnits: 2}
	// SYP currency struct
	SYP = Currency{code: "SYP", minorUnits: 2}
	// TWD currency struct
	TWD = Currency{code: "TWD", minorUnits: 2}
	// TJS currency struct
	TJS = Currency{code: "TJS", minorUnits: 2}
	// TZS currency struct
	TZS = Currency{code: "TZS", minorUnits: 2}
	// THB currency struct
	THB = Currency{code: "THB", minorUnits: 2}
	// TOP currency struct
	TOP = Currency{code: "TOP", minorUnits: 2}
	// TTD currency struct
	TTD = Currency{code: "TTD", minorUnits: 2}
	// TND currency struct
	TND = Currency{code: "TND", minorUnits: 3}
	// TRY currency struct
	TRY = Currency{code: "TRY", minorUnits: 2}
	// TMT currency struct
	TMT = Currency{code: "TMT", minorUnits: 2}
	// UGX currency struct
	UGX = Currency{code: "UGX", minorUnits: 0}
	// UAH currency struct
	UAH = Currency{code: "UAH", minorUnits: 2}
	// AED currency struct
	AED = Currency{code: "AED", minorUnits: 2}
	// USN currency struct
	USN = Currency{code: "USN", minorUnits: 2}
	// UYU currency struct
	UYU = Currency{code: "UYU", minorUnits: 2}
	// UYI currency struct
	UYI = Currency{code: "UYI", minorUnits: 0}
	// UZS currency struct
	UZS = Currency{code: "UZS", minorUnits: 2}
	// VUV currency struct
	VUV = Currency{code: "VUV", minorUnits: 0}
	// VEF currency struct
	VEF = Currency{code: "VEF", minorUnits: 2}
	// VND currency struct
	VND = Currency{code: "VND", minorUnits: 0}
	// YER currency struct
	YER = Currency{code: "YER", minorUnits: 2}
	// ZMW currency struct
	ZMW = Currency{code: "ZMW", minorUnits: 2}
	// ZWL currency struct
	ZWL = Currency{code: "ZWL", minorUnits: 2}
	// XBA currency struct
	XBA = Currency{code: "XBA", minorUnits: 0}
	// XBB currency struct
	XBB = Currency{code: "XBB", minorUnits: 0}
	// XBC currency struct
	XBC = Currency{code: "XBC", minorUnits: 0}
	// XBD currency struct
	XBD = Currency{code: "XBD", minorUnits: 0}
	// XTS currency struct
	XTS = Currency{code: "XTS", minorUnits: 0}
	// XXX currency struct
	XXX = Currency{code: "XXX", minorUnits: 0}
	// XAU currency struct
	XAU = Currency{code: "XAU", minorUnits: 0}
	// XPD currency struct
	XPD = Currency{code: "XPD", minorUnits: 0}
	// XPT currency struct
	XPT = Currency{code: "XPT", minorUnits: 0}
	// XAG currency struct
	XAG = Currency{code: "XAG", minorUnits: 0}
)

var currencies = map[string]Currency{
	"AFN": AFN,
	"EUR": EUR,
	"ALL": ALL,
	"DZD": DZD,
	"USD": USD,
	"AOA": AOA,
	"XCD": XCD,
	"ARS": ARS,
	"AMD": AMD,
	"AWG": AWG,
	"AUD": AUD,
	"AZN": AZN,
	"BSD": BSD,
	"BHD": BHD,
	"BDT": BDT,
	"BBD": BBD,
	"BYN": BYN,
	"BZD": BZD,
	"XOF": XOF,
	"BMD": BMD,
	"INR": INR,
	"BTN": BTN,
	"BOB": BOB,
	"BOV": BOV,
	"BAM": BAM,
	"BWP": BWP,
	"NOK": NOK,
	"BRL": BRL,
	"BND": BND,
	"BGN": BGN,
	"BIF": BIF,
	"CVE": CVE,
	"KHR": KHR,
	"XAF": XAF,
	"CAD": CAD,
	"KYD": KYD,
	"CLP": CLP,
	"CLF": CLF,
	"CNY": CNY,
	"COP": COP,
	"COU": COU,
	"KMF": KMF,
	"CDF": CDF,
	"NZD": NZD,
	"CRC": CRC,
	"HRK": HRK,
	"CUP": CUP,
	"CUC": CUC,
	"ANG": ANG,
	"CZK": CZK,
	"DKK": DKK,
	"DJF": DJF,
	"DOP": DOP,
	"EGP": EGP,
	"SVC": SVC,
	"ERN": ERN,
	"ETB": ETB,
	"FKP": FKP,
	"FJD": FJD,
	"XPF": XPF,
	"GMD": GMD,
	"GEL": GEL,
	"GHS": GHS,
	"GIP": GIP,
	"GTQ": GTQ,
	"GBP": GBP,
	"GNF": GNF,
	"GYD": GYD,
	"HTG": HTG,
	"HNL": HNL,
	"HKD": HKD,
	"HUF": HUF,
	"ISK": ISK,
	"IDR": IDR,
	"XDR": XDR,
	"IRR": IRR,
	"IQD": IQD,
	"ILS": ILS,
	"JMD": JMD,
	"JPY": JPY,
	"JOD": JOD,
	"KZT": KZT,
	"KES": KES,
	"KPW": KPW,
	"KRW": KRW,
	"KWD": KWD,
	"KGS": KGS,
	"LAK": LAK,
	"LBP": LBP,
	"LSL": LSL,
	"ZAR": ZAR,
	"LRD": LRD,
	"LYD": LYD,
	"CHF": CHF,
	"MOP": MOP,
	"MKD": MKD,
	"MGA": MGA,
	"MWK": MWK,
	"MYR": MYR,
	"MVR": MVR,
	"MRU": MRU,
	"MUR": MUR,
	"XUA": XUA,
	"MXN": MXN,
	"MXV": MXV,
	"MDL": MDL,
	"MNT": MNT,
	"MAD": MAD,
	"MZN": MZN,
	"MMK": MMK,
	"NAD": NAD,
	"NPR": NPR,
	"NIO": NIO,
	"NGN": NGN,
	"OMR": OMR,
	"PKR": PKR,
	"PAB": PAB,
	"PGK": PGK,
	"PYG": PYG,
	"PEN": PEN,
	"PHP": PHP,
	"PLN": PLN,
	"QAR": QAR,
	"RON": RON,
	"RUB": RUB,
	"RWF": RWF,
	"SHP": SHP,
	"WST": WST,
	"STN": STN,
	"SAR": SAR,
	"RSD": RSD,
	"SCR": SCR,
	"SLL": SLL,
	"SGD": SGD,
	"XSU": XSU,
	"SBD": SBD,
	"SOS": SOS,
	"SSP": SSP,
	"LKR": LKR,
	"SDG": SDG,
	"SRD": SRD,
	"SZL": SZL,
	"SEK": SEK,
	"CHE": CHE,
	"CHW": CHW,
	"SYP": SYP,
	"TWD": TWD,
	"TJS": TJS,
	"TZS": TZS,
	"THB": THB,
	"TOP": TOP,
	"TTD": TTD,
	"TND": TND,
	"TRY": TRY,
	"TMT": TMT,
	"UGX": UGX,
	"UAH": UAH,
	"AED": AED,
	"USN": USN,
	"UYU": UYU,
	"UYI": UYI,
	"UZS": UZS,
	"VUV": VUV,
	"VEF": VEF,
	"VND": VND,
	"YER": YER,
	"ZMW": ZMW,
	"ZWL": ZWL,
	"XBA": XBA,
	"XBB": XBB,
	"XBC": XBC,
	"XBD": XBD,
	"XTS": XTS,
	"XXX": XXX,
	"XAU": XAU,
	"XPD": XPD,
	"XPT": XPT,
	"XAG": XAG,
}

// ValidCodes is provided so that you may build your own validation against it
var ValidCodes = []string{
	"AFN",
	"EUR",
	"ALL",
	"DZD",
	"USD",
	"AOA",
	"XCD",
	"ARS",
	"AMD",
	"AWG",
	"AUD",
	"AZN",
	"BSD",
	"BHD",
	"BDT",
	"BBD",
	"BYN",
	"BZD",
	"XOF",
	"BMD",
	"INR",
	"BTN",
	"BOB",
	"BOV",
	"BAM",
	"BWP",
	"NOK",
	"BRL",
	"BND",
	"BGN",
	"BIF",
	"CVE",
	"KHR",
	"XAF",
	"CAD",
	"KYD",
	"CLP",
	"CLF",
	"CNY",
	"COP",
	"COU",
	"KMF",
	"CDF",
	"NZD",
	"CRC",
	"HRK",
	"CUP",
	"CUC",
	"ANG",
	"CZK",
	"DKK",
	"DJF",
	"DOP",
	"EGP",
	"SVC",
	"ERN",
	"ETB",
	"FKP",
	"FJD",
	"XPF",
	"GMD",
	"GEL",
	"GHS",
	"GIP",
	"GTQ",
	"GBP",
	"GNF",
	"GYD",
	"HTG",
	"HNL",
	"HKD",
	"HUF",
	"ISK",
	"IDR",
	"XDR",
	"IRR",
	"IQD",
	"ILS",
	"JMD",
	"JPY",
	"JOD",
	"KZT",
	"KES",
	"KPW",
	"KRW",
	"KWD",
	"KGS",
	"LAK",
	"LBP",
	"LSL",
	"ZAR",
	"LRD",
	"LYD",
	"CHF",
	"MOP",
	"MKD",
	"MGA",
	"MWK",
	"MYR",
	"MVR",
	"MRU",
	"MUR",
	"XUA",
	"MXN",
	"MXV",
	"MDL",
	"MNT",
	"MAD",
	"MZN",
	"MMK",
	"NAD",
	"NPR",
	"NIO",
	"NGN",
	"OMR",
	"PKR",
	"PAB",
	"PGK",
	"PYG",
	"PEN",
	"PHP",
	"PLN",
	"QAR",
	"RON",
	"RUB",
	"RWF",
	"SHP",
	"WST",
	"STN",
	"SAR",
	"RSD",
	"SCR",
	"SLL",
	"SGD",
	"XSU",
	"SBD",
	"SOS",
	"SSP",
	"LKR",
	"SDG",
	"SRD",
	"SZL",
	"SEK",
	"CHE",
	"CHW",
	"SYP",
	"TWD",
	"TJS",
	"TZS",
	"THB",
	"TOP",
	"TTD",
	"TND",
	"TRY",
	"TMT",
	"UGX",
	"UAH",
	"AED",
	"USN",
	"UYU",
	"UYI",
	"UZS",
	"VUV",
	"VEF",
	"VND",
	"YER",
	"ZMW",
	"ZWL",
	"XBA",
	"XBB",
	"XBC",
	"XBD",
	"XTS",
	"XXX",
	"XAU",
	"XPD",
	"XPT",
	"XAG",
}
